### ISSUE TITLE
Review from TAG should be requested prior to Member review

### ISSUE THREAD

**Issue by csarven** [solid/solid-wg-charter#15]
As part of horizontal review, review from TAG should be requested to improve the charter prior to going to Members.

There will most certainly be clarifications requested on how the Solid Protocol (and related works) fit with other W3C works. For example, LDP, ActivityPub.

Other considerations will be: major unresolved issues or oppositions to design.

Possibly other details like how was the work funded...

Clarifications on how well the work fits within the ethical web principles and societal impact (see also https://solidproject.org/TR/protocol#considerations )

**Comment by pchampin** [comment]
More generally, horizontal reviews will be requested before the AC review, indeed.

**Comment by csarven** [comment]
This topic was deliberated, at least in e.g., [CG meetings](https://github.com/search?q=repo%3Asolid%2Fspecification%20path%3A%2F%5Emeetings%5C%2F%2F%20https%3A%2F%2Fgithub.com%2Fsolid%2Fsolid-wg-charter%2Fissues%2F15&type=code) and possibly elsewhere.

The [2023-09 version of the Solid WG charter proposal](https://www.w3.org/2023/09/proposed-solid-wg-charter.html) did not benefit from a TAG review because the feedback wasn't available until after the Members had reviewed it. Put differently, the request/recommendation in this issue was not followed.

The [TAG review](https://github.com/w3c/strategy/issues/377#issuecomment-1790209071) of the 2023-09 charter proposal is now available.
