### ISSUE TITLE
Constraining the scope to client-to-server specifications

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-wg-charter#23]
Initial conversations for the charter of this group focused deliberately on advancing the **client-to-server** parts of the Solid W3C Community Group into a W3C Working Group.

However, the current contents also contain one client-to-client aspect:

> 1. Define a core protocol specification for the secure and efficient operation of Solid servers and the behavior of clients interacting with those servers.
> 1. Recommend a data and protocol model **for interoperability between multiple applications built upon Solid**.
> 1. Recommend a set of practices needed for data security for Solid Pods, and for both server and client software, including use of appropriate authentication, authorization, verification, identity, and other standards, integrating existing outside efforts.
> 1. Recommend a set of protocol behaviors and best practices for the use in Solid of the OpenID Connect (OIDC) / Federation identity layer on top of the OAuth 2.0 protocol.
> 1. Recommend a set of protocol behaviors and best practices to request and grant access to data stored in Solid Pods.
> 1. Define a protocol for state synchronization regarding changes to resources in Solid pods.

Given that all other points focus on client-to-server interactions, it seems that point 2 above is out of scope for the first charter of the Working Group. Also note that is has been omitted from the section of proposed details:

> 1. OpenID Connect
> 1. Access management and data integrity using Verifiable Credentials Data Model
> 1. Identity mechanisms such as WebID and DID
> 1. Notifications about resource changes using Solid Notifications Protocol
> 1. Authorization mechanisms such as Web Access Control and Access Control Policy

As such, I propose removing this point 2 from the charter scope, or at least amending it such that it is no longer about client-to-client interoperability but client-to-server.

**Comment by timbl** [comment]
Agreed. The current scope of the working group should include all protocols the sever knows about but not client-client specs.

**Comment by csarven** [comment]
Agreed.

See also https://github.com/solid/solid-wg-charter/issues/9
