### ISSUE TITLE
Equal wording for all investigated technologies

### ISSUE THREAD

**Issue by kaefer3000** [solid/solid-wg-charter#29]
Different sections are differently affirmative about the technologies to be investigated.

Section 2 "Scope" rightly talks about many different ends (authentication, security, state synchronisation, ...) that the Solid Protocol should achieve. Section 2 mentions one specific means to achieve an end (authentication), the technology OpenID Connect. OIDC may be a good choice to achieve authentication, but this looks imbalanced.

Similar imbalance can be found in Section 3.1 "Normative Specifications": The proposed charter mentions WebID, DID, Web Access Control, and Access Control Policies, only as examples ("such as"), however the proposed charter mentions Verifiable Credentials, OpenID Connect, and Solid Notifications Protocol more affirmatively, that is, without saying that they serve merely as examples.

Therefore, I propose to remove the mention of OIDC from 2. Scope, and to introduce all technologies in 3.1 Normative Specifications with "such as".

(thanks to @uvdsl for the discussion on this issue)

**Comment by csarven** [comment]
I generally agree with your suggestions. With the interest to reducing overlapping issues, may I ask you to share your comment in https://github.com/solid/solid-wg-charter/issues/9 and then we can close this issue?

There is a PR on revising the Deliverables section: https://github.com/solid/solid-wg-charter/pull/28#issue-1664501308 that we're likely to wrap up soon. I think some of what you say is aligned with that PR, and you're welcome to review that. We can make a separate PR for the Scope (once that's through).

**Comment by kaefer3000** [comment]
Regarding 2: :heavy_check_mark: 

Regarding 3.1: Am I right that you are referring to this line in the revised Deliverables section: https://github.com/solid/solid-wg-charter/blob/dad42a27481505399927c6f6055f42cf3335ac2c/charter/index.html#L255

**Comment by csarven** [comment]
Thanks. re 3.1 / Deliverables, partly yes. That particular sentence is sufficient as catch-all about integration. The actual deliverables and intended are listed now. That leaves us to iron out the Scope section.
