### ISSUE TITLE
Improve readability of opening sentence

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-wg-charter#35]
The opening sentence reads:

> It is common for web service providers to require that users store their data in a way that is often restricted to certain systems or can only be accessed by the applications that created it, while also requiring users to surrender control over their own data.

The readability is hindered by the length of the opening clause, which is 35 words long.  Consider splitting this into two sentences, or adding punctuation.

**Comment by pchampin** [comment]
Would the following be more readable?

> It is common for web service providers to require users to surrender control over their own data, and store them in a way that is often restricted to certain systems, or can only be accessed by the applications that created it.

I basically changed the order of the two requirements, starting with the shortest one, and factorizing a little more. The drawback is that the "surrender control" argument is given less weight, IMO.

**Comment by melvincarvalho** [comment]
> It is common for web service providers to require users to surrender control over their own data, and store them in a way that is often restricted to certain systems, or can only be accessed by the applications that created it.

I like this.  I played around with it a bit, and came up with this.  

Possibly some more food for thought.

> Web service providers often mandate users to cede control of their data, which is then stored in a fashion typically limited to certain systems or only accessible by the applications responsible for its creation.

Trying to avoid bike-shedding here.  But it might be a good time investment to have a good opening sentence.

**Comment by csarven** [comment]
Thanks both. Pierre-Antoine's edit works for me as well. Committed https://github.com/solid/solid-wg-charter/commit/45d6dfbae7ed536d5ae816949771be45a1f039ab .
