### ISSUE TITLE
[question] will rdf 1.2 be part of Solid 1.0?

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-wg-charter#36]
The inclusion of RDF-Star, also known as RDF 1.2, in the Coordination section piqued my interest. I was wondering if it is in scope into Solid 1.0, or if it's destined for a future version? 

I understand that a definitive decision may not have been reached yet. Still, any indication or guidance text would be very valuable for implementaters.

The natural assumption would be that as RDF progresses it will eventually make its way into the solid suite of specifications.  Clarification on whether or not that assumption is correct would be good.

**Comment by csarven** [comment]
Good question. As far as I know, considerations apply to all successor versions of references, as well as errata, and other information, e.g., plans of a group working on the specification, and so it is within the scope. I would suggest to not put any emphasis on the versions or even specific data formats in the charter. The group can best make those decisions with the most accurate context.

On a related note, the Considerations section of the Solid Protocol gives general advisory about the status of documents in https://solidproject.org/TR/protocol#considerations .
