### ISSUE TITLE
Consider adopting WebID 1.0 ED as a Deliverable

### ISSUE THREAD

**Issue by csarven** [solid/solid-wg-charter#39]
I propose that the Solid WG charter should adopt the [WebID 1.0 ED](https://www.w3.org/2005/Incubator/webid/spec/identity/) as a Deliverable, if of course the [WebID CG](https://www.w3.org/groups/cg/webid) agrees.

There is **plethora** of publishing and implementation experience, as well as use of WebIDs in the wild, I would strongly suggest that the Solid WG should only focus on translating Web 1.0 ED - what is seemingly a document equivalent to the maturity of level of a Proposed Recommendation, that's been around forever but needs some love - to a REC. I would also suggest that the specification should not introduce breaking changes, and should continue to stand on its own. The specification is currently developed at https://github.com/w3c/WebID/ .

IMO, this would undoubtedly be mutually beneficial for the WebID CG and Solid CG/WG, as well as other Groups, and the WebID-based ecosystems that use the specification today.

---

As the Scope/Out of Scope section is written in https://github.com/solid/solid-wg-charter/pull/38 , I would not consider WebID to be out of scope. However, if an agreement can be reached, we should update the Scope and Deliverables section to clarify that.

**Comment by melvincarvalho** [comment]
If my recollection is accurate, the integration into the LDP charter was nearly achieved, but ultimately it wasn't included. Logically speaking, it might be appropriate for it to be a part of Solid, given this is its origin.

**Comment by bblfish** [comment]
yes, that makes sense.

**Comment by langsamu** [comment]
I support this proposal.

I am the lead contributor to recent commercial implementations of WebID and ACP, and a contributor to recent commercial implementations of the Solid Protocol and Solid-OIDC.

My experience is that WebID is practically, if not theoretically, indispensable for Solid. For this reason I should think the working group is highly incentivized to adopt it. I would consider the effort an excellent investment.

I also think that the draft is implementable as it stands. Not just on its own but as part of the wider context I have experience developing and supporting. Hence I agree that the effort should be restricted to translating the draft to a recommendation.

If only I never again hear the words "but it's just a draaaaaft".

**Comment by pchampin** [comment]
What is the relation between the WebID CG's ED [WebId](https://www.w3.org/2005/Incubator/webid/spec/identity/) and the SOlid CG's report [Solid WebId Profile](https://solid.github.io/webid-profile/)? Seems to me that if they were to be adopted by the Solid WG, they should be merged into one document?

Also, I have mixed feelings about this. One the one hand, recall that this WG is meant to focus on the client-to-server interactions (the Solid Protocol *per se*), as opposed to the client-to-client conventions (vocabularies, shapes...) that are also part of the full Solid landscape. On the one hand, WebID seems to belong to the 2nd category. On the other hand, as @langsamu points out, it is so core to everything in Solid (starting with authentication, if I am correct?), that having a standard Solid Protocol without a standard for WebID seems strange.

**Comment by jeff-zucker** [comment]
> What is the relation between the WebID CG's ED [WebId](https://www.w3.org/2005/Incubator/webid/spec/identity/) and the SOlid CG's report [Solid WebId Profile](https://solid.github.io/webid-profile/)?

The WebID spec defines what a generic (not Solid-specific) WebID is.  The Webid-Profile spec defines how a WebID is used in Solid and specifically, the organization and purpose of the Solid WebID Profile.  The relationship between a WebID Profile Document (which may or may not be on a Solid Resource Server) and a Solid Profile is part of what the CG is working on.

**Comment by jeff-zucker** [comment]
I agree that the WG should take on the WebID 1.0. ED as a deliverable.

**Comment by melvincarvalho** [comment]
@elf-pavlik 

> A WebID [Profile Document](https://www.w3.org/2005/Incubator/webid/spec/identity/#dfn-profile_document) is a Web resource that MUST be available as text/[turtle](https://www.w3.org/2005/Incubator/webid/spec/identity/#bib-turtle) [turtle], but MAY be available in other RDF serialization formats (e.g. [[RDFA-CORE](https://www.w3.org/2005/Incubator/webid/spec/identity/#bib-RDFA-CORE)]) if requested through content negotiation.

This was the definition about 10 years ago.  There has been a lot of modernization since then and discussions in the CG.  In short JSON-LD has matured and gained significant adoption in the intervening time period.

Recent consensus has gravitated towards using Turtle and JSON-LD as the primary serializations, a direction which I believe is in harmony with Solid's approach. If needed, we can initiate a brief discussion thread within the CG to affirm this understanding (i.e., Turtle + JSON-LD).

**Comment by melvincarvalho** [comment]
FYI: the WebID CG is currently developing a document that reflects our collective consensus from 2014 to 2023. For instance, we've agreed unanimously and without objection that JSON-LD should be mentioned in light of its significant deployment post-2014 ( https://lists.w3.org/Archives/Public/public-webid/2020Aug/0000.html ).

We are working through a temporary challenge with chair responsiveness, as we currently have only one chair. However, the group is actively looking for solutions, to this issue.

But, I'm optimistic we can collaborative to produce a specification that is agreeable to all.  Perhaps we'll need a bit of interaction between the start of the WG and FPWD, depending on how quickly things go.

**Comment by bblfish** [comment]
It think we agreed that JSON-LD is a good addition. Why not just wait for the Solid WG? JSON-LD is already part of LDP, so I don't think it would be a problem. Those who want to deploy with json-ld already are welcome to do it.

**Comment by melvincarvalho** [comment]
@bblfish

Our group has transitioned to a 'lazy consensus' approach for decision-making to ensure the diverse views of all members are represented. Please refer to this for more detail: https://lists.w3.org/Archives/Public/public-webid/2023Jul/0042.html.

**Comment by bblfish** [comment]
Melvin, you agreed to the move to the WG on June 1st here 
 
https://lists.w3.org/Archives/Public/public-webid/2023Jun/0000.html

We left everybody time to answer and I did not see anyone against this move, hence the commit here.

**Comment by melvincarvalho** [comment]
The commit is fine.  I am pointing out some new information, that the consensus of the group, particularly for the years 2014-2023 is being documented, in preparation, to work together with the solid WG.  And that the group has moved to lazy consensus.  The current consensus is coalescing around an idea that could potentially please everyone in the WebID CG and in the Solid WG:  

https://lists.w3.org/Archives/Public/public-webid/2023Jul/0056.html

**Comment by jacoscaz** [comment]
Hi all, and particularly @csarven . 

In the WebID CG group we're trying a new approach to get out of the long-standing impasse. Tracking the conversation across both GitHub and mailing lists is hard and time-consuming, so I thought I'd provide some context here and invite feedback from the Solid WG.

Quoting my comment from https://github.com/w3c/WebID/issues/21#issuecomment-1829403570 :

> Here's a few links that might help to contextualize this:
>
> New chair: https://lists.w3.org/Archives/Public/public-webid/2023Nov/0121.html
> Nathan's superspec/subspec proposal: https://lists.w3.org/Archives/Public/public-webid/2023Jul/0056.html , originating in https://github.com/w3c/WebID/issues/17
> Super-early superspec draft: https://jacoscaz.com/WebID/superspec/webid.html
>
> Fundamentally, the idea is to produce a minimal WebID "superspec" (I think another word to describe it would be a framework spec) focusing on the underlying concepts and mechanisms of WebIDs while leaving serialization formats (Turtle, JSON-LD, ...) and specific features (TLS, OIDC, ...) up to subspecs.
> 
> The end result should, of course, be functionally compatible with the current version of the spec. The intention is not to create something functionally different but, rather, to re-organize the spec so as to overcome the current impasse and finally get to WebID 1.0.

As one of the primary implementors of WebID, feedback from the Solid WG is particularly welcome.
