### ISSUE TITLE
Best deadline for the AC review?

### ISSUE THREAD

**Issue by pchampin** [solid/solid-wg-charter#41]
I have just requested Horizontal Review on the charter proposal : https://github.com/w3c/strategy/issues/377 .

Once we get them, we can submit the charter proposal to the W3C members (AC Review). We need to leave at least 28 days, and as a rule we don't set voting deadlines during August. So we will probably set the deadline in the first half of September.

We then have a choice:
* setting it in the first week of September, just *before* [TPAC](https://www.w3.org/2023/09/TPAC/), so we can have our first WG meeting there, or
* setting it in the second week of September, *during* TPAC, which gives us the opportunity to discuss face-to-face with members that would have questions about the charter.

The 2nd option forces us to wait a little longer, but not significantly much (~1 week), and I think the F2F discussions during TPAC might be useful.

Any opinion?

**Comment by elf-pavlik** [comment]
> The 2nd option forces us to wait a little longer, but not significantly much (~1 week), and I think the F2F discussions during TPAC might be useful.

:+1: to the 2nd option. Having a face-to-face opportunity to clarify anything that might be raised over the next weeks could come helpful.

On the other side, Solid CG already has a meeting scheduled. I'm not sure what benefits would come out of relabeling that meeting as a Solid WG meeting. If the WG would get approved just a few days before TPAC, would it even be enough time for people to officially join the WG as [Member Representative](https://www.w3.org/2023/Process-20230612/#member-rep-wg) or as [Invited Expert](https://www.w3.org/2023/Process-20230612/#invited-expert-wg) in such a short time span, especially with WG chairs *TBD*.

**Comment by melvincarvalho** [comment]
Suggest selecting chairs and completing the voting process prior to the first face-to-face meeting at TPAC. Perhaps the WG would then only need another 2-3 more F2F in total.  

Given that there are already have two implementations and a test suite, and the W3C director is leading the project, there's reason to be optimistic about favorable voting (fingers crossed!). 

Unless significant objections are anticipated, perhaps aim for an early September timeline, with a contingency of reserving TPAC for any necessary clarifications should any unforeseen issues arise.

**Comment by pchampin** [comment]
On 2nd thought, I realized that :
* if everything goes smoothly (fingers crossed), then the sooner the better;
* if some members vote against the charter proposal, then we will have to discuss with them to try and settle their objections (https://www.w3.org/2023/Process-20230612/#team-fo-mediation).

TPAC will be a great place to have this conversation, and so it is probably better to have the whole week for this. If the deadline is during TPAC, then some objections may arrive late, and leave us less time to try and settle them.

**Comment by elf-pavlik** [comment]
Thanks for the clarification @pchampin, in that case, it looks like it is actually safer to go with the 1st option.
I think you can just go ahead with it since I can't see any reason why would anyone now prefer the 2nd option.

**Comment by laurensdeb** [comment]
I agree with the first option, having the face-to-face time to settle any objections will be more productive and allow us to tackle specific points of contention.

Moreover, TPAC would give us good momentum to kickstart the WG efforts and organize ourselves for the work ahead.

**Comment by melvincarvalho** [comment]
Gentle bump.  Was any decision made on this?

**Comment by melvincarvalho** [comment]
Update in the original issue:

https://github.com/w3c/strategy/issues/377#issuecomment-1709106503

**Comment by pchampin** [comment]
> Gentle bump. Was any decision made on this?

Well, the horizontal review took more time than expected, so the question as framed in this issue has become moot.
The charter proposal has been *finally* [sent to the AC](https://lists.w3.org/Archives/Public/public-new-work/2023Sep/0007.html), with a deadline on 2023-10-06.
