### ISSUE TITLE
Inclusion of HTML in Solid

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-wg-charter#42]
Upon searching for "HTML" in both: 

[Solid Protocol 0.10](https://solidproject.org/TR/2022/protocol-20221231) and [PROPOSED Solid Working Group Charter](https://solid.github.io/solid-wg-charter/charter/)

it appears that HTML is not mentioned as a delivery mechanism for Solid. Considering it's the primary interface for most users and developers interacting with Solid, should we include a mention of HTML, as being in scope, in either of these documents?

**Comment by csarven** [comment]
I think explicitly mentioning HTML (or any other format) would be too specific for this particular Charter . And depending on what's being mentioned, it is possibly Out of Scope, e.g., there'd be other Groups that be more suitable that extends the HTML specification. That aside, if there is a particular proposal for a requirement involving HTML, that can be made against the ED at https://github.com/solid/specification . What do you think?

**Comment by melvincarvalho** [comment]
I couldn't help but notice that HTML, the primary method of interaction, isn't mentioned.

You might consider the approach taken in version 0.7 of the Solid Specification (https://github.com/solid/solid-spec), where HTML was more effectively integrated into the narrative.

**Comment by elf-pavlik** [comment]
Doing quick search https://github.com/search?q=repo%3Asolid%2Fsolid-spec+HTML&type=code

I don't see many mentions of HTML in 0.7, what do you refer to specifically?

**Comment by melvincarvalho** [comment]
@elf-pavlik for example how would solid be used in the browser, when someone clicks a webid hyperlink?

More could be said about what would return, the profiles, the social web, and linked data.  

While I don't hold a rigid standpoint on the exact manner of incorporating HTML into this conversation, I find its complete absence somewhat puzzling, as it was mentioned in previous versions.

**Comment by csarven** [comment]
Aside: Official minutes of the CG are published on the solid/specification repository ( https://github.com/solid/specification/blob/main/meetings/2023-07-12.md )

It is true that https://github.com/solid/solid-spec/blob/master/README.md mentions HTML in the context of RDFa, i.e., using it as one of the concrete RDF syntaxes. That said, solid/specification and the publications under TR/protocol (specifically v0.9, v0.10), ED/protocol (v0.11) supersedes and clarifies v0.7.

The understanding in the meeting ( https://github.com/solid/specification/blob/main/meetings/2023-07-12.md#inclusion-of-html-in-solid ) was that discussion can continue: the general agreement among those that chimed in the meeting was that the consideration should be done against the Solid Protocol as opposed to the WG Charter.

Closing issue. All, to rebring the spirit of HTML+RDFa mention in Solid Protocol v0.7 into the current work on v0.11, please follow up in https://github.com/solid/specification , in particular the document https://github.com/solid/specification/blob/main/ED/protocol.html ( or https://solidproject.org/ED/protocol ).

**Comment by melvincarvalho** [comment]
> to rebring the spirit of HTML

The idea of revitalizing the spirit of HTML resonates with me!

> All, to rebring the spirit of HTML+RDFa

However, when it comes to combining HTML with RDFa, I respectfully differ. In my view, using structured data islands might serve us better for multiple reasons. They're typically more widely adopted, can't be PATCHed, and seem to align more with the consensus within the Solid and WebID groups.

Of course, the final decision is up to the collective group. I just wanted to express my reservation towards RDFa, hence a strong -1 to that serialization from my side.

> Closing issue

Thank you! I'm eager to see how the discussion progresses and what solutions the group develops.
