### ISSUE TITLE
Is Solid still Social Linked Data?

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-wg-charter#43]
Looking at the recent [Solid Protocol 0.10](https://solidproject.org/TR/2022/protocol-20221231) and the [PROPOSED Solid Working Group Charter](https://solid.github.io/solid-wg-charter/charter/), I observed that there's no explicit mention of the Social Web or Social Linked Data.

Sites where Solid is named "Social Linked Data" include [wikipedia](https://en.wikipedia.org/wiki/Solid_(web_decentralization_project)) and [MIT](https://solid.mit.edu/).

Given the original conception of "Solid" was to add the social web to linked data, and subsequently the acronym "Solid" for "SOcial LInked Data," was coined, by  @sandhawke . I am curious if the focus on this concept has shifted over time.

**Comment by sandhawke** [comment]
Even at the time, the acronym wasn't the best fit.  It was chosen because the Social Web Working Group was considering three major directions, and we kept talking about this one but didn't have a name for it. In that context the name makes more sense. 

Also, I'll note that https://en.wikipedia.org/wiki/Social_computing is much broader that "Social media", and that much of the motivation for solid was to allow people to move easily between competing apps. That was something we didn't know how to do even if we wanted to, when the apps were social. There's a kind of lock in, Social Lock-In that gives that software a huge barrier to entry against competition.  So, in that sense, most of the advantage of Solid for humanity comes from its use in Social computing.

**Comment by melvincarvalho** [comment]
@sandhawke thanks for the response, I had not heard of [Social Computing](https://en.wikipedia.org/wiki/Social_computing) before, but it makes sense.

Solid was more to do with the [Social Web](https://en.wikipedia.org/wiki/Social_computing), IMHO

> The Web is more a social creation than a technical one. I designed it for a social effect—to help people work together—and not as a technical toy. The ultimate goal of the Web is to support and improve our weblike existence in the world -- Tim Berners-Lee

While the term "Social Linked Data" was in use as far back as [2012](https://lists.w3.org/Archives/Public/public-lod/2012Jun/0170.html) I first recorded it at as acronym [here in March 2015](https://www.w3.org/community/rww/2015/03/31/read-write-web-q1-summary-2015/).  This was based on the [minutes](https://www.w3.org/wiki/Socialwg/2015-03-18-minutes) from the Social Web F2F in the same month.

It's actually not all that clear who came up with SoLiD (the elite capitalization later dropped).  Reading the minutes again, perhaps a few people came up with it at the same time e.g. (@evanp, @sandhawke , @hhalpin).

Also note Evan's [comment](https://github.com/solid/solid-spec/issues/18#issuecomment-99044699):

> I thought the whole point of SoLiD (= Social Linked Data) was to apply the Linked Data Platform to the user stories of the Social API. I thought the name was created at the last F2F, even.

And Sandro's [response](https://github.com/solid/solid-spec/issues/18#issuecomment-99056547)

> +1 @evanp

Solid being short Social Linked data has been mentioned ever since, and as recently as [2022](https://vinfutureprize.org/laureates/professor-sir-tim-berners-lee-om-kbe-frs-freng-frsa/)

In light of this, I am curious if there has been a shift in its definition that might not have been documented, or if it's an unintentional omission.

**Comment by sandhawke** [comment]
What I recall is a SWWG F2F in Stata and going to break with the charge of coming up with a name for it. I'd been thinking about "SoLiD" a little bit, wondering if there was something better.  But with the end-of- break deadline approaching, I asked Tim if he thought SoLiD was okay,  and he said yes, so we went with it. It's possible someone had suggested it first, and/or I'm mis-remembering, but that's what I've got.

**Comment by melvincarvalho** [comment]
Some comments from [tantek](https://www.w3.org/2023/09/22-social-minutes.html):

> tantek: Some may be aware of solid

> tantek: It was originally about social web hence the name solid is short for "social linked data" but now it seems like it has shifted to personal data stores

Is it accurate that solid has transitioned from its social web origins to focus more on personal data stores?  I've always seen solid as a social web initiative. Input from those familiar at TPAC would be appreciated.

**Comment by melvincarvalho** [comment]
So question for the WG Charter authors.  Does Solid stand for "Social Linked Data"?

The word social doesnt appear in the charter.  If, yes, Solid still means "Social Linked Data" it should say that in the text.

**Comment by csarven** [comment]
I suppose some folks started to use "SoLiD" as "Solid", and perhaps with no particular emphasis on "social" and/or "linked data".

Though, I wouldn't go so far as saying that it shifted from"social linked data" to "personal data stores". The Web is inherently social, so it is not we need to be reminded of "social". "Personal" is not particularly accurate either despite some making it seem like it is all about "pod"s or informally (and sometimes incorrectly) lumping everything into together.


If anything, using TimBL speak, Solid would be "socially-aware" storage

**Comment by melvincarvalho** [comment]
> Does it matter if Solid is still "Social Linked Data" or not?

Yes, very much so, hence the very specific question!

We all know the web is social.

Either Solid (SoLiD) stands for "Social Linked Data", in which, case that can be confidently stated, and it SHOULD be stated in the charter and/or protocol.

Or it doesnt.

One of these two options must be picked.  If it doesnt stand for "social linked data" then the spec or charter, that should be stated.

**Comment by melvincarvalho** [comment]
Related to this question is Tantek's review:

https://lists.w3.org/Archives/Public/public-new-work/2023Oct/0007.html

**Comment by melvincarvalho** [comment]
Closing as this topic has been inactive 8 months.  Can be reopened if there's interest.
