### ISSUE TITLE
Motiviation still seems a bit vague

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-wg-charter#44]
> It is common for web service providers to require users to surrender control over their own data, and store them in a way that is often restricted to certain systems, or can only be accessed by the applications that created it.
>
> Solid extends open web standards to give priority to individual and community autonomy, allowing them to keep authority over their identity, data, and privacy, and giving them the freedom to select applications and services that suit their needs.

Particularly: **"store them in a way that is often restricted to certain systems"** sounds vague.  What systems?

Also: **"allowing them to keep authority over their identity, data, and privacy"** is also a bit vague.  Solid doesn't really do this, it allows you to co-own your identity and data with a provider.

It's not all that clear as a motivation e.g. it doesnt explain how it differs from dropbox, from s3, from webdav, from remotestorage etc.

Perhaps a better story can be told about this, and the solution provided, similar to stories used to promote federated models such as activitypub.

**Comment by pchampin** [comment]
Hopefully, the [recent changes](https://github.com/solid/solid-wg-charter/pull/69) clarify this.

> Solid doesn't really do this.

Well, the charter does not claim that it does. It sets this as a goal of its own deliverable(s).

> Perhaps a better story can be told about this.

Perhaps. Feel free to submit a PR. In the meantime, closing this.
