### ISSUE TITLE
Clarifying "Achieve Them" in Deliverables Section

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-wg-charter#45]
> In this environment, actors allocate identifiers for their content, shape and store data where they have access to, set access controls, and use preferred applications and services to achieve them.

It's not entirely clear what "achieve them" was referring to

**Comment by pchampin** [comment]
I agree that this "achieve them" is strange, I didn't notice that before...

Since this is a quote from another document, we are not free to change it. An easy solution would be to replace the "to achieve them" with "(...)". Luckily, the sentence still makes sense (more sense, arguably).

**Comment by pchampin** [comment]
I'll include this change in PR #72, because the corresponding text is already touched by this PR. This is better, IMO, than creating two conflicting PRs.
