### ISSUE TITLE
Consider marking DID out of scope

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-wg-charter#54]
Given the notable formal objections to DID work in the past, including from a past chair of the Social Web Working Group, it's worth reconsidering the inclusion of explicit mention of DID work in the charter. While I initially held a neutral stance, observing its progress has raised concerns, particularly due to the vast number of sub specifications involved, each with varying quality. 

For the best chance of success for Solid, it might be prudent to sidestep potential controversy by excluding it from the charter. The charter already encompasses ample identity-related topics.

**Comment by melvincarvalho** [comment]
> as well as to advance an understanding of whether a Solid-specific DID method is needed

It's an unnecessary risk IMHO.  It may likely result in technical objection down the line.  But if that's acceptable, let's cross that bridge when we come to it.

**Comment by pchampin** [comment]
>  But if that's acceptable, let's cross that bridge when we come to it.
Does it mean that you agree to close this issue?

**Comment by melvincarvalho** [comment]
> Does it mean that you agree to close this issue?

No objection to it being closed.  It can be revisited after the WG starts.

**Comment by melvincarvalho** [comment]
Having read the comments on the new PUMPKIN WG, I sense that DID is being used in the same breath as WebID as an identity system

I think a WebID based solid, or something very close to WebID as the identity system of solid should be taken forward.

I dont think the door should be left open in either PUMPKIN or SOLID for DID, and it's 100+ subspecs to be in scope for identity, because it could easily increase the complexity, and cause lots of political issues as proponents vie to get their preferred block chain to become part of solid identity.

Strong -1 on DID inclusion as things stands, as it is way premature for v1.0.

Strong +1 on using WebID, or a tweaked version of WebID, which is an HTTP identifier that returns RDF.  That has been the bedrock of solid for over a decade.

**Comment by melvincarvalho** [comment]
Let me add this post from Kingsley on the WebID mailing list, to support the thesis:

https://lists.w3.org/Archives/Public/public-webid/2023Nov/0163.html

> DiD has nothing to do with neither Solid nor WebID. Mangling them will be a disaster, to put things mildly.

**Comment by pchampin** [comment]
@melvincarvalho I'm closing this issue, following [a discussion of the CG](https://github.com/solid/specification/blob/main/meetings/2024-04-03.md#wg-charter-proposal) (which, incidentally, you are also welcome to join).

The argument (which I made earlier) is that it must be a WG decision to rule out DIDs or not. Preventing the WG to even discuss this would be interpreted as "we charter to WG to produce a pre-conceived solution rather than explore the problem space", which was one of the main arguments of several formal objections on the charter.
