### ISSUE TITLE
conduct issue

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-wg-charter#55]
Consider pausing the WG charter until this credible conduct issue is resolved, as it affects, test suite, reference implementations, reputation of the project, and the potential structure of the WG

https://forum.solidproject.org/t/migrating-from-nss-to-css/6856/5

**Comment by elf-pavlik** [comment]
Could you please clarify you reasoning why a tension between specific members of broad Solid community should affect Solid WG moving forward? 

> as it affects, test suite, reference implementations, reputation of the project, and the potential structure of the WG

Could you provide more details on how this situation would impact all what you are mentioning?

**Comment by melvincarvalho** [comment]
@elf-pavlik we've both known Michiel for over 10 years and know that his reports are credible:

> After years in the Solid community I and others have gotten used to the bullying, but that doesn’t make it OK. Let’s stick to our spirit of open collaboration and friendly manners.

See also the quote in the thread from Emelia:

> The people in the wrong here have repeatedly acted like this towards many many community members, even driving some away, or at least contributing to an unhealthy environment which drove them away.

The issues raised extend beyond isolated incidents or private matters. In fact, additional community members have come forward to corroborate a pattern of bullying that has, regrettably, driven some away and contributed to an unhealthy environment. As we are on the verge of launching a new Working Group, it's absolutely critical that these serious allegations are addressed collectively. Leaving such concerns unaddressed risks casting a long shadow over the future and integrity of the project.

**Comment by melvincarvalho** [comment]
@elf-pavlik the chairs are certainly a big consideration.  I didnt know that the two chairs had been published on the w3.org site.  Thank you for the info.

**Comment by michielbdejong** [comment]
Just seeing this issue now - fully agree with @elf-pavlik that it's unrelated to the current WG charter and the currently proposed co-chairs.

**Comment by melvincarvalho** [comment]
@elf-pavlik regarding the comments from the public institution Imec:

>     Michiel,
>    I repeat: please leave our employees alone.
>    I am […], and we certainly don’t have to spend time contacting you.
>    That decision is final, so you can stop doing it.

>    The reason we don’t interact with you is because 1) **you don’t have the necessary technical competencies**, and 2) you’re just out to steal people’s time to put yourself in the spotlight. The entire community has already lost months of work on interactions with you, and **we as Ghent University/imec** will no longer go along with that.

>    **You are the stereotype of an attention-addicted narcissist**, which is why [we] need to protect [our] employees from wasting our precious time.
**>    Go steal other people’s time**, you will **get more applause and spotlights there. But not from us**. Jamais.

Would you agree that this conduct is unacceptable?  What steps have been taken?

**Comment by elf-pavlik** [comment]
> Edit: would appreciate if you were able to share the relevant meeting minutes.

https://hackmd.io/7hxOQtEmRwmbF_WwOYzjEg#conduct-issue

Soon also archived in: https://github.com/solid/specification/pull/591

**Comment by elf-pavlik** [comment]
> Would you agree that this conduct is unacceptable?

I agree that we can do better and I understand that the person who have written the harsh word [also agreed in retrospective (an apology)](https://lists.w3.org/Archives/Public/public-solid/2023Sep/0056.html)

I also would like to notice that the conduct happened in private (direct) email exchange. Besides that the contention point was related to an open source software which is not a direct work item of the CG.

Last but not least, the person who was directly targeted with the harsh word [agrees that this incident shouldn't affect process of WG creation](https://github.com/solid/solid-wg-charter/issues/55#issuecomment-1784658882)

> What steps have bee taken.

As I mentioned, a public apology was issued for the words said over a private conversation. Other than empathizing even stronger the [Code of Conduct](https://github.com/solid/process/blob/main/code-of-conduct.md) published by the CG, I don't see any further actions that need to be taken.

> Consider pausing the WG charter until this credible conduct issue is resolved, 

There is a very strong rough consensus that in no way this incident grants such a drastic reaction. I believe that there might be even a full consensus among all the [**active** CG participants](https://virginiabalseiro.github.io/solid-ecosystem-monitor/#present-bar-chart)

> I'd further point out this https://github.com/solid/solid-wg-charter/pull/48#pullrequestreview-1593463307:

>> Moving forward, imec aims to play a strong role in bot the standardization work within the WG, and incubation work in the CG.

Please keep in mind that Solid WG will operate under W3C Process: https://www.w3.org/2023/Process-20230612/#discipline
> Participants in any W3C activity **MUST** abide by the terms and spirit of the [W3C Code of Ethics and Professional Conduct](https://www.w3.org/Consortium/cepc/) [[CEPC]](https://www.w3.org/2023/Process-20230612/#biblio-cepc) and the participation requirements described in “Disclosure” in the W3C Patent Policy [[PATENT-POLICY]](https://www.w3.org/2023/Process-20230612/#biblio-patent-policy).

If you don't have trust in current W3C Process, please consider raising an issue upstream.

-----

@melvincarvalho based on the further responses to the linked mailing list thread I understood that you have [personal history and possible resent](https://lists.w3.org/Archives/Public/public-solid/2023Sep/0058.html) which resonated with this situation. While everyone's emotional well being is important, please reflect if possibly an old personal grudge might be playing a role in motivating your reaction represented in this issue.

------

> Alternatively, I'd also appreciate an opinion @pchampin

I believe that @pchampin as W3C Team Contact should have a the final word and let's all commit to trusting in his judgement.

**Comment by melvincarvalho** [comment]
> I believe that @pchampin as W3C Team Contact should have a the final word

:+1:

**Comment by csarven** [comment]
>@elf-pavlik the chairs are certainly a big consideration. I didnt know that the two chairs had been published on the w3.org site. Thank you for the info.

>I think the only situation when this incident could affect formation of WG would be a case when the person with misconduct allegation was proposed as a WG chair.

* https://github.com/solid/solid-wg-charter/pull/56#issuecomment-1762155425
* https://github.com/solid/solid-wg-charter/pull/47#issuecomment-1690387640
* https://github.com/solid/specification/discussions/576

**Comment by csarven** [comment]
This issue was opened on 2023-09-28 and the CG has deliberated on the proposal to "[c]onsider pausing the WG charter until this credible conduct issue is resolved".

In the [2023-11-01 CG meeting](https://github.com/solid/specification/blob/main/meetings/2023-11-01.md#conduct-issue), the group agreed to close this issue.

@pchampin or the W3C Team in general can indeed have the "final word" as they're now aware of @melvincarvalho 's request. That said, any or further consideration on changing the progress status of the proposed charter is out of scope for this repository, as I've mentioned in the 2023-11-01 meeting.

**Comment by pchampin** [comment]
As I have been "summoned"...

I don't have much to add to @elf-pavlik's very good [summary above](https://github.com/solid/solid-wg-charter/issues/55#issuecomment-1789486026). Without minimizing the importance of good conduct in general, nor of this misconduct in particular, I believe it does not justify hindering the chartering process.
