### ISSUE TITLE
Tantek's feedback re 2 / 3 chairs

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-wg-charter#66]
> We have questions about how the Team selected WG chairs without apparent consideration of the existing CG chair. This looks improper and worth objecting to until an explanation is made clear.

I'm fairly sure all input was considered, and knowing solid very well, I think exceptionally good, and practical, selections were made.

I think two chairs is absolutely fine, given there are already 2 implementations and a test suite.  Aaron is highly regarded, well known to the community, has excellent technical knowledge and people skills.

I'm sure an explanation could be offered if necessary.

> * Is Solid WG really a thinly veiled Inrupt WG? We would like to see explicit disclosures on the existence of any financial relationships between Inrupt and any consulting companies that are supporters or contributing staff to this effort.

If a 3rd chair is added, in the interests of diversity and inclusion, please dont let it be someone that has worked for Inrupt in the last year.  That would give Inrupters 2/3rd chair majority, which is bad optics, and I dont think they really need it.  On top of that the Solid Director is Inrupt CTO.

Justin could be a good choice, as he has always been a pragmatist, and has industry experience.

Elf seemed to want more responsibility, and has open source experience.

But I think in general a 3rd chair would only delay the deliverables.  Instead better to have more invited experts participate, who can argue their case without the need to be neutral.  An IE can be more effective than a chair in terms of contributing to a spec.

We all want to see Solid get to REC sooner rather than later, so better to put aside personal ambitions, and work as a team to get the spec over the line.

**Comment by pchampin** [comment]
This issue is already tracked in the W3C charter repo: w3c/charter-drafts#455.

Closing as duplicate.
