### ISSUE TITLE
What are the Solid User Stories?

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-wg-charter#67]
It the charter it says:

"Solid servers and applications across a wide range of use cases. "

Which points to:

https://github.com/solid/user-stories

A repository that has not changed for 3 years.  Someone visiting that link or the [issues](https://github.com/solid/user-stories/issues) page will be none the wiser as to what Solid does

The question was even asked over a year ago which of these use cases have been implemented.  No one could answer.

What actually can Solid do today?  Which of the use cases are compelling, can get broad adoption, and are actually working?

**Comment by pchampin** [comment]
The goal of this link is to demonstrate that the Solid community has worked on gathering user stories. This repository is evidence for that, and it can be used as a starting point by the WG (which, as the charter proposal points out, is expected to revisit and extend it).

It could be more fresh and/ore more detailed, but it is in my view better than nothing.
