### ISSUE TITLE
Open session to discuss and promote Solid WG charter proposal

### ISSUE THREAD

**Issue by csarven** [solid/solid-wg-charter#68]
* Revise Solid WG charter.
* Communicate / coordinate / incorporate goals of Solid WG including similar initiatives and works.
* Promote pre-PROPOSAL or PROPOSAL for Solid WG.

Perhaps this is something @pchampin (W3C Team) can follow up on to widely communicate in a public space where anyone interested can discuss and coordinate even if it is just an informative session. Explain progress since https://www.w3.org/2023/09/proposed-solid-wg-charter.html e.g., outline significant objections / concerns are (being) addressed as well as the work/proposal ahead, including Solid CG (and friends) decisions and W3C *Team Decisions*.

Considering using these kinds of important sessions to promote the WG charter to the W3C community, as well as to gather and incorporate feedback prior to making the second (upcoming) Solid WG charter proposal.

There was https://www.w3.org/2024/01/webevolve-series-events/solid.html but I don't see a record of this event being mentioned to the public Solid CG or any particular feedback to the Solid CG or the Solid WG charter. Perhaps it wasn't necessary or useful.

There is [W3C Breakouts Day 2024](https://www.w3.org/2024/03/breakouts-day-2024/) on 2024-03-12 for breakout sessions, I suggest [proposing a session](https://github.com/w3c/breakouts-day-2024/issues/new?assignees=&labels=session&projects=&template=session.yml) towards this end. More details at https://github.com/w3c/breakouts-day-2024  Example proposal for WG charter: https://github.com/w3c/breakouts-day-2024/issues/3

**Comment by melvincarvalho** [comment]
I was hoping the WG would start up in early 2024, and then get to REC in early 2026 since it already has 2 implementations and a test suite.

Are you saying that you think the WG will still not be chartered by mid March?

**Comment by pchampin** [comment]
@csarven I'd be happy to have this conversation. The W3C breakout day is indeed a good opportunity, althouh I kinda hope we can be into horizontal review already at that point, or even AC review (though the latter seems overly optimistic).

@melvincarvalho given that the minimum delay for the AC review is 28 days, we will definitely not have a WG mid March. But as I write above, I hope we have some progress towards that by then.

Re. the [WebEvolve](https://www.w3.org/2024/01/webevolve-series-events/solid.html) meeting about Solid, I concur that it would have been nice to advertise it to the CG. Note however that the event was mostly in Chinese (apart from my presentation), and Zoom's live translation was only barely helpful...

**Comment by melvincarvalho** [comment]
Can this be closed?

**Comment by hzbarcea** [comment]
Yes, it can and should be.
