### ISSUE TITLE
Update mission

### ISSUE THREAD

**Issue by csarven** [solid/solid-wg-charter#7]
>The <strong>mission</strong> of the <a class=todo href="">Solid Working Group (LINK TBD)</a> is to standardize the Solid Protocol and its use of associated data interoperability and authentication schemes. This effort will culminate in open standards that can be used by developers of servers and applications to continue to build a rich ecosystem that returns control of data back to users.

Marking this as issue for now because the mission doesn't seem to flow well.

The current content is more like goal(s) rather than a mission.

"its use of" is still under incubation. What's "associated data interoperability" exactly? Clarify with links if need to.

It focuses on control but that's just one aspect of what Solid Protocol or set of technical reports. "Social" is very much core to Solid. See also https://www.w3.org/DesignIssues/CloudStorage for some background.

**Comment by woutermont** [comment]
Just a thought. Do we distinguish between the mission(s) of the Solid Project, Solid CG, and Solid WG?

- Do they all have the same mission/ends, which they help progress by working towards different goals/means (awareness, incubation, delivery ...)? (In which case some update is needed.) 

- Or are the missions/ends of the Solid CG and Solid WG rather goals/means of the Solid Projects? (In which case no update seems needed.)

**Comment by VirginiaBalseiro** [comment]
>  This effort will culminate in open standards that can be used by developers of servers and applications to continue to build a rich ecosystem that returns control of data back to users.

This sentence is vague and unclear as to the core objectives of the WG. It should clearly articulate the purpose of the group and what it aims to achieve.

It mentions the standardization of the Solid Protocol, but it doesn't specify the benefits or outcomes of this standardization. It would be helpful to highlight the potential impact or advantages that these open standards will bring.

Moreover, phrases like "rich ecosystem" and "returns control of data back to users" are a bit vague and don’t provide specific details about what these mean or how they will be achieved. 

I think the CG charter’s description of mission and tasks is clear:
> The mission of the [Solid Community Group](https://www.w3.org/groups/cg/solid/) is to explore and describe the interoperability between different classes of products by using Web communication protocols, global identifiers, authentication and authorization mechanisms, data formats and shapes, notifications, and query interfaces.
> The task of the group includes drafting and incubating proposed technical specifications for further standardization and prototyping and testing implementations.

Maybe going through this description and reflecting on how the WG’s mission and goals differ from these would be a good exercise to go through to produce a clearer definition for WG.

**Comment by pchampin** [comment]
Should be solved by #69.
