### ISSUE TITLE
Charter should limit the scope of idenity to HTTP based identifiers

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-wg-charter#70]
In alignment with the principles of simplicity and efficiency, it is suggested that any charter pertaining to PUMKIN or SOLID specifically confines its identity scope to HTTP-based identifiers, thereby excluding DIDs from consideration. This recommendation is grounded in the understanding that incorporating multiple identities markedly increases both the complexity and security landscape, alongside introducing significant political dimensions.

It's pertinent to note that over the course of fifteen years, a functional system that is both testable and applicable across various applications using HTTP and returning RDF has been developed. This accomplishment underscores the feasibility and effectiveness of HTTP identifiers, which, while inheriting attributes from URIs, prove to be fully compatible.

In the interest of progressing towards a operational framework with at least two implementations and a comprehensive test suite in an expedited manner, it is proposed that Solid 1.0 exclusively utilizes HTTP URIs. This approach not only aligns with our immediate objectives but also ensures a streamlined focus on achieving Recommendation status (REC) with HTTP URIs, which itself presents a substantial challenge.

Explorations into alternative identity systems may be pursued in distinct forums or considered subsequent to Solid's advancement to REC utilizing HTTP URIs.

**Comment by pchampin** [comment]
this issue is a variation on #54, closing as duplicate
