### ISSUE TITLE
Please upvote and downvote proposed WG names

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-wg-charter#75]
The goal here is to pick a name that describes the mission of this WG, namely:
> [...] to enable the development of web applications where data storage, entity authentication, access control, and application provider are all loosely coupled, as opposed to the web of today where these are typically all tightly coupled and changing one requires changing all, sometimes at the price of all past data. This will be achieved by standardizing a protocol between client-side applications, on the one hand, and identity and storage providers, on the other hand.

Please click the face icon and then thumbs-up (👍 ) under the name(s) you think are fitting and/or thumbs-down (👎 ) under the name(s) you think are not.

**Comment by michielbdejong** [comment]
Enquire Within WG

**Comment by michielbdejong** [comment]
Fixing the Web WG

**Comment by michielbdejong** [comment]
Remote Storage WG

**Comment by michielbdejong** [comment]
Control Yourself WG

**Comment by michielbdejong** [comment]
Personal Storage WG

**Comment by michielbdejong** [comment]
Linked Web Storage WG

**Comment by michielbdejong** [comment]
Social Linked Data WG

**Comment by michielbdejong** [comment]
Linked HTTP storage WG

**Comment by michielbdejong** [comment]
Personal Data Store WG

**Comment by michielbdejong** [comment]
Sovereign Linked Data WG

**Comment by michielbdejong** [comment]
Bring Your Own Storage WG

**Comment by michielbdejong** [comment]
Self-owned Linked Data WG

**Comment by michielbdejong** [comment]
Socially-aware Storage WG

**Comment by michielbdejong** [comment]
Protected Data Platform WG

**Comment by michielbdejong** [comment]
Social and Personal Data WG

**Comment by michielbdejong** [comment]
Personal Linked Data Store WG

**Comment by michielbdejong** [comment]
Samaritan Owned Linked Data WG
(still solid WG)

**Comment by michielbdejong** [comment]
Decentralized Online Storage WG
(DOS WG)

**Comment by michielbdejong** [comment]
Sovereign Secure Data Spaces WG

**Comment by michielbdejong** [comment]
Protected Linked Data Platform WG

**Comment by michielbdejong** [comment]
Sovereign Secure Linked Data Spaces WG

**Comment by michielbdejong** [comment]
Decentralization and Democratization WG
(D&D WG)

**Comment by michielbdejong** [comment]
Semantically Integrating Data and Apps WG
(SIDAWG)
(pronounced sea-dawg)

**Comment by michielbdejong** [comment]
Semantically Linked Decentralized Data WG

**Comment by michielbdejong** [comment]
Decentralized Online Storage & Identity WG
(Dosanti WG)

**Comment by michielbdejong** [comment]
Self-owned Linked Information Depository WG

**Comment by michielbdejong** [comment]
Distributed Apps, Identities, and Storages WG
(DAIS WG)
A dais or daïs is a raised platform at the front of a room or hall, usually for one or more speakers or honored guests.

**Comment by michielbdejong** [comment]
Samaritan Owned Linked Information Depository WG
(actually SOLID WG)

**Comment by michielbdejong** [comment]
Semantically Integrating Distributed Data and Apps WG
(SIDDAWG)
(pronounced sea-dawg)

**Comment by michielbdejong** [comment]
Apps, Multi-identity, and Authentication for Distributed Environments of URL/URI Storages WG
(AMADEUS WG)

**Comment by michielbdejong** [comment]
--- ENDS ---

Please don't put comments under this, we can keep using #73 for discussions, process and backgrounds on why we upvote or downvote something

**Comment by hzbarcea** [comment]
This issue should have been closed long ago.
