### ISSUE TITLE
Coordination with the Federated Identity Working Group

### ISSUE THREAD

**Issue by acoburn** [solid/solid-wg-charter#77]
The current charter text already [mentions](https://solid.github.io/solid-wg-charter/charter/#background) the Federated Identity CG but does not list this group in the [Coordination](https://solid.github.io/solid-wg-charter/charter/#coordination) section. I assume this is just an oversight.

Furthermore, the Federated Identity CG has now been chartered as a [working group](https://www.w3.org/groups/wg/fedid/), so it would make more sense to list the WG in this document rather than the CG.

**Comment by elf-pavlik** [comment]
@thhck made an extension for CSS https://github.com/fedidcg/FedCM/issues/240#issuecomment-2098673274
